### ISSUE TITLE
update to 0.2.9 - ckeditor5 - django admin doesn´t work

### ISSUE THREAD

**Issue by gomezschall** [hvlads/django-ckeditor-5#160] opened 2023-08-04 14:19 UTC
I have been using django-ckeditor-5==0.2.7 in my Django app. I had configured the settings according to the instructions, and everything was working fine so far. I use CKEditor windows both in the admin panel and in templates. However, when I update to django-ckeditor-5==0.2.9, the CKEditor in the admin panel no longer functions properly. The text windows are displayed without formatting but with HTML tags. When I downgrade back to version 0.2.7, everything works well again.

here are my other packages:
asgiref==3.7.2 # ASGI Interface (Webserver Gunicorn communication)
Django==4.2.4 # Python web framefwork
psycopg==3.1.9 # postgres new interface version
psycopg-binary==3.1.9 # postgres new interface version
sqlparse==0.4.4 # sql parser
tzdata==2023.3 # timezone data
django-crispy-forms==2.0 # better forms
crispy-bootstrap5==0.7 # better forms
django-allauth==0.54.0 # login and more
django-phonenumber-field[phonenumberslite]==7.1.0 # telephonenumber library
environs[django]==9.5.0 # env
whitenoise==6.5.0 # better static behavior
django_reverse_admin==2.9.6 # is this needed ?
reportlab==3.6.13 # pdf generator -from version 4.0 there were errors in the execution
Pillow==9.5.0 # image library
django-cleanup==8.0.0 # delete files from filestructure after deleting link in admin
django-auto-logout==0.5.1 # the name stands for itself
django-admin-relation-links==0.2.5 # used it in TVSerie to link Blocks
django-debug-toolbar==4.1.0 # developper analyse tool
django-clone==5.3.3 # to copy deliveries
django-admin-inline-paginator==0.4.0 # used at Django Adming Project inline -> Deliveries
django-ckeditor-5==0.2.9 # wysiwig text input / update to 0.2.9 crashes the input widgets in admin
sentry-sdk==1.29.2 # error tracking

**Comment by hvlads** [comment] 2023-08-06 17:17
It seems like you are experiencing an issue with the CKEditor in the admin panel after upgrading to `django-ckeditor-5==0.2.9`. To help troubleshoot the problem, it would be useful to have more information. Could you please provide the error messages or any relevant logs from the Django application and the browser console?

Additionally, before proceeding with the troubleshooting, I recommend trying the following steps:

1. Pre-clean the browser cache: Sometimes, outdated cached files can cause unexpected behavior after an upgrade. Clearing your browser's cache might help resolve the issue. You can find instructions on how to clear the cache for various browsers online.

2. Verify the CKEditor configuration: Ensure that you have correctly configured CKEditor in your Django settings.

3. Review the browser console: If the issue persists, open the browser console (usually accessible through the F12 key or right-clicking on the page and selecting "Inspect" or "Inspect Element"). Look for any error messages or warnings related to CKEditor or other JavaScript components. Share these error messages with us so we can better understand the issue.

Once you have gathered more information from the browser console and any relevant logs, please share them with us or provide more details about the specific issue you are facing. This will enable us to assist you further in resolving the problem or suggest possible solutions. If the issue persists and you believe it might be a bug or compatibility issue, consider opening an issue on the `django-ckeditor-5` GitHub repository, providing the relevant details and steps to reproduce the problem. This way, the package maintainers and the community can look into it and help resolve the issue.

**Comment by gomezschall** [comment] 2023-08-07 08:43
in my browser developer console appears this:

Uncaught TypeError: document.getElementById(...) is null
    yC app.js:31
    <anonymous> app.js:71
[app.js:31:36](webpack://django_ckeditor_5/static/django_ckeditor_5/app.js)
    yC app.js:31
    <anonym> app.js:71
    
    is that helpful ?

**Comment by gomezschall** [comment] 2023-08-07 10:13
i tried to install version 0.2.8 and the ckeditor5 admin panel window worked. so the problem appears in the version 0.2.9

**Comment by hvlads** [comment] 2023-09-10 13:46
Hello, @gomezschall  I have installed all the packages you mentioned and everything is working for me. Unfortunately, I couldn't reproduce the issue.

**Closed** 2023-09-23 16:41 UTC
